const copy = {
en: {brand:'a little world of wonder',navAbout:'About Pei',navWork:'Selected work',navContact:'Say hello',heroKicker:'ILLUSTRATION · STORIES · EVERYDAY WONDER',heroTitle:'A little world,\ndrawn with wonder.',heroText:'For the stories we imagine,\nand the little joys we find along the way.',heroLink:'Wander through my work ↓',heroCaption:'One moment. One meeting. A world of possibilities.',aboutKicker:'A NOTE FROM THE ARTIST',aboutTitle:'Hello, I’m Pei.',aboutNote:'Lovely to meet you here.',aboutLead:'I make pictures that hold a little warmth,\na little curiosity, and a reason to smile.',aboutBody:'I’m a freelance illustrator exploring children’s stories, playful stationery, digital watercolour and Chinese cultural motifs. Seasons, small creatures and everyday moments find their way into my sketchbook.',aboutBody2:'This is a place to share those discoveries, with art lovers, exhibition organisers and anyone who enjoys a small escape into an illustrated world.',secretHint:'psst…',secretText:'You found a little friend. May something lovely find you today, too.',workKicker:'FROM MY SKETCHBOOK',workTitle:'Stories in colour.',workIntro:'A few places my imagination has wandered.',all:'All work',story:'Storytelling',paper:'Paper & little things',water:'Watercolour',culture:'Culture & tradition',galleryNote:'Choose a picture to take a closer look.',contactKicker:'A LITTLE LETTER, A NEW CONNECTION',contactTitle:'Let’s say hello.',contactText:'For artwork conversations and exhibition enquiries,\nyou’ll find me on Instagram.',footer:'Made of little moments. Artwork rights reserved.',top:'Back to the treetops ↑'},
zh: {brand:'把日常畫成小小的美好',navAbout:'關於 Pei',navWork:'精選作品',navContact:'打聲招呼',heroKicker:'插畫 · 故事 · 日常的小美好',heroTitle:'用畫筆，\n收藏一個小世界。',heroText:'把想像中的故事，\n與日常遇見的小小喜悅，畫成美好。',heroLink:'走進我的作品 ↓',heroCaption:'一期一會，每一次相遇都有新的可能。',aboutKicker:'來自創作者的小小問候',aboutTitle:'你好，我是 Pei。',aboutNote:'很開心，在這裡遇見你。',aboutLead:'希望畫裡有一點溫暖、一點好奇，\n還有讓人會心一笑的小事。',aboutBody:'我是一位自由插畫工作者，創作涵蓋繪本兒插、文創小品、數位水彩與國潮插畫。四季的變化、小動物的世界與日常片刻，都會悄悄走進我的畫本。',aboutBody2:'這裡收藏了我的創作與發現，歡迎喜愛藝術的朋友、展覽策劃者，以及想走進插畫世界的人一起欣賞。',secretHint:'偷偷告訴你…',secretText:'你找到了一位小夥伴。願今天也有一件美好的小事，悄悄找到你。',workKicker:'從我的畫本裡',workTitle:'讓色彩說故事。',workIntro:'跟著想像力，走過幾個小地方。',all:'全部作品',story:'繪本與故事',paper:'紙品與小物',water:'水彩水墨',culture:'文化與國潮',galleryNote:'點選作品，看看畫裡的小細節。',contactKicker:'一封小信，一次新的相遇',contactTitle:'來打聲招呼吧。',contactText:'作品交流與展覽相關洽詢，\n歡迎透過 Instagram 聯絡我。',footer:'收藏日常的小美好。作品版權保留。',top:'回到樹梢 ↑'},
ja: {brand:'日々の小さな喜びを描く',navAbout:'Peiについて',navWork:'作品',navContact:'お問い合わせ',heroKicker:'イラスト · 物語 · 日々の小さな喜び',heroTitle:'小さな世界に、\n想像の彩りを。',heroText:'思い描く物語と、\n日々の中で見つけた小さな喜びを。',heroLink:'作品の世界を歩く ↓',heroCaption:'一期一会。出会いから、新しい世界へ。',aboutKicker:'作者からの小さなごあいさつ',aboutTitle:'こんにちは、Peiです。',aboutNote:'ここで出会えて、うれしいです。',aboutLead:'少しのぬくもりと、少しの好奇心。\n思わず笑顔になる絵を描きたい。',aboutBody:'フリーランスのイラストレーターとして、絵本、文具や雑貨、デジタル水彩、中国の伝統文化を現代的に表現するイラストを制作しています。季節の移ろい、小さな生き物、日常のひとこまが、スケッチブックに息づいています。',aboutBody2:'ここでは、創作の中で見つけた小さな発見をご紹介します。アートが好きな方、展覧会を企画する方、イラストの世界を楽しみたい方に届けば幸いです。',secretHint:'こっそり…',secretText:'小さな仲間を見つけましたね。今日、あなたにも素敵なことが訪れますように。',workKicker:'スケッチブックから',workTitle:'色彩でつづる物語。',workIntro:'想像のままに歩いた、いくつかの小さな世界。',all:'すべて',story:'絵本と物語',paper:'文具と小さな雑貨',water:'水彩',culture:'文化と伝統',galleryNote:'作品を選んで、小さな細部までご覧ください。',contactKicker:'小さな手紙、新しいつながり',contactTitle:'お話ししませんか。',contactText:'作品や展覧会に関するお問い合わせは、\nInstagramからお願いいたします。',footer:'日々の小さな瞬間から。作品の無断転載・使用はご遠慮ください。',top:'木のてっぺんへ ↑'}
};
const works = [
[6,'story','Christmas by the Snowing Window','聖誕節窗外的雪景','雪の窓辺のクリスマス'],
[12,'paper','Halloween’s Little Witch','十月萬聖節的小魔女','ハロウィンの小さな魔女'],
[22,'water','Summertime and Lotus','夏日荷花','夏と蓮の花'],
[26,'water','Little Rabbit Exploring','森系小兔子小發現','小さなうさぎの発見'],
[18,'paper','Meow Meow’s Sweet Love','喵喵的小甜甜愛','ねこたちの小さな愛'],
[29,'culture','Auspicious Festivals','粗線國潮 · 節慶好日子','縁起のよいお祭り'],
[24,'water','Autumnal Equinox','秋分與故人的時光','秋分、友人とのひととき'],
[16,'paper','Colourful Autumn Leaves','秋葉繽紛多彩','色とりどりの秋の葉'],
[33,'culture','Empress Xia’s Crown','線性國潮 · 孝靜毅皇后的皇冠','皇后の鳳冠'],
[35,'culture','Snowy Days, Hotpot Days','天天下雪，火鍋天天','雪の日は火鍋の日'],
[37,'culture','Guizhou and Its Winery','貴州釀酒之佳','貴州の風景と酒造り'],
[9,'story','803 Anti-Scam Guidebook','803 反詐：全民防騙指南','803 詐欺防止ガイドブック']
];
let language = 'en', filter = 'all', currentArt = null;
const gallery = document.querySelector('#gallery'), dialog = document.querySelector('#art-dialog');
const reduced = matchMedia('(prefers-reduced-motion: reduce)');
const observer = 'IntersectionObserver' in window ? new IntersectionObserver(entries => entries.forEach(e => {if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.08}) : null;
function titleOf(work){return work[{en:2,zh:3,ja:4}[language]];}
function showArt(work){currentArt=work;const img=document.querySelector('#dialog-img');img.src=`assets/work-${work[0]}.jpg`;img.alt=titleOf(work);document.querySelector('#dialog-title').textContent=titleOf(work);document.querySelector('#dialog-category').textContent=copy[language][work[1]];document.querySelector('#dialog-subtitle').textContent=language==='en'?work[3]:work[2];dialog.showModal();}
function renderGallery(){gallery.replaceChildren();works.filter(w=>filter==='all'||w[1]===filter).forEach(work=>{const card=document.createElement('article');card.className='card';const button=document.createElement('button');button.className='art-button';button.setAttribute('aria-label',titleOf(work));const img=document.createElement('img');img.src=`assets/work-${work[0]}.jpg`;img.alt=titleOf(work);img.loading='lazy';img.width=600;img.height=600;button.append(img);button.addEventListener('click',()=>showArt(work));const label=document.createElement('p');label.className='eyebrow';label.textContent=copy[language][work[1]];const title=document.createElement('h3');title.textContent=titleOf(work);const subtitle=document.createElement('p');subtitle.textContent=language==='en'?work[3]:work[2];card.append(button,label,title,subtitle);gallery.append(card);if(observer&&!reduced.matches){card.classList.add('reveal');observer.observe(card);}});}
function setLanguage(next){language=next;document.documentElement.lang={en:'en',zh:'zh-Hant',ja:'ja'}[next];document.querySelectorAll('[data-i18n]').forEach(el=>{el.replaceChildren();copy[next][el.dataset.i18n].split('\n').forEach((line,i)=>{if(i)el.append(document.createElement('br'));el.append(document.createTextNode(line));});});document.querySelectorAll('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lang===next)));document.querySelector('.dialog-close').setAttribute('aria-label',{en:'Close artwork',zh:'關閉作品',ja:'作品を閉じる'}[next]);document.querySelector('.secret').setAttribute('aria-label',{en:'Discover a little secret',zh:'發現一個小秘密',ja:'小さな秘密を見つける'}[next]);renderGallery();}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang)));
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderGallery();}));
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',event=>{if(event.target===dialog){const box=dialog.getBoundingClientRect();if(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom)dialog.close();}});
document.querySelector('.secret').addEventListener('click',event=>{const button=event.currentTarget,note=document.querySelector('#secret-note');note.hidden=!note.hidden;button.setAttribute('aria-expanded',String(!note.hidden));});
let lastSpark=0;
document.addEventListener('click',event=>{if(reduced.matches||!matchMedia('(pointer:fine)').matches||event.detail===0||Date.now()-lastSpark<120)return;lastSpark=Date.now();for(let i=0;i<5;i++){const spark=document.createElement('span');spark.className='spark';spark.textContent=i%2?'✧':'·';spark.style.left=`${event.clientX}px`;spark.style.top=`${event.clientY}px`;spark.style.setProperty('--sx',`${(i-2)*18}px`);spark.style.setProperty('--sy',`${-25-Math.random()*30}px`);document.body.append(spark);setTimeout(()=>spark.remove(),850);}});
setLanguage('en');
